

class Autogenerated {
  late bool status;
  late  Data data;



  Autogenerated.formJson(Map<String, dynamic> json) {
    status = json['status'];
    data =  new Data.formJson(json['data']) ;
  }

}

class Data {
  int? currentPage;
  late List<Data2a> Data2=[];
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  String? path;
  int? perPage;
  int? to;
  int? total;



  Data.formJson(Map<String, dynamic> json) {
    currentPage = json['current_page'];
    firstPageUrl = json['first_page_url'];
    from = json['from'];
    lastPage = json['last_page'];
    lastPageUrl = json['last_page_url'];
    path = json['path'];
    perPage = json['per_page'];
    to = json['to'];
    total = json['total'];
    json['data'].forEach((v) {
      Data2.add(Data2a.formJson(v));
    });

  }


}

class Data2a {
 late int id;
  String? name;
  String? image;



  Data2a.formJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    image = json['image'];
  }


}